name: CI Pipeline
on:
  push:
   branches:[main]
  pull_reaquest:
   branches:[main]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses:actions/checkout
      - name:installer python
      - uses:actions/setup-python
        with:
          python-version:"3.11"
      - name:Installer Dependences 
      - run:pip install -r requirements.txt
      - name:Installer flake
      - run:pip install flake8
      - name:Lancer les tests
test :
  needs:lint 
  